sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull crystallang/crystal:0.24.1
  - docker run -v `pwd`:/root/scry crystallang/crystal /bin/sh -c "cd /root/scry; crystal spec"
